"""Add daily_investment field to scans table

Revision ID: 41809e99215a
Revises: a96f2d439160
Create Date: 2025-09-05 23:44:06.655787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '41809e99215a'
down_revision: Union[str, None] = 'a96f2d439160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = {column['name'] for column in inspector.get_columns('scans')}

    if 'daily_investment' not in existing_columns:
        op.add_column(
            'scans',
            sa.Column('daily_investment', sa.Numeric(precision=10, scale=2), nullable=True),
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'daily_investment')
    # ### end Alembic commands ###
